/********************************************************************
 * Module       : port                                              *
 * File Name    : port_PBcfg.c                                      *
 * Description  : Post build configuration for port driver          *
 * Author       : Mohamed Ashraf                                    *
 ********************************************************************/

#include "port.h"



PORT_ConfigType configurations = {
   {{(u8)0 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)1 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)2 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)3 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)4 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)5 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)6 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)7 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)8 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)9 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)10, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)11, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)12, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)13, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)14, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)15, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)16, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)17, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)18, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)19, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)20, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)21, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)22, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)23, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)24, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)25, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)26, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)27, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)28, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)29, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)30, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)31, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)32, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)33, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{(u8)34, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}}
};
